name: online-payment-platform

services:
  server:
    image: server
    build:
      context: ../../
      dockerfile: deployments/docker/server/Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=online_payment_platform
      - ACQUIRING_BANK_URL=http://simulator:8090
    ports:
      - 8080:8080