name: online-payment-platform

services:
  postgres:
    extends:
      file: postgres.yml
      service: postgres

  pgadmin:
    extends:
      file: postgres.yml
      service: pgadmin


volumes:
  postgres-data: